AWSTemplateFormatVersion: '2010-09-09'
Description: A simple EC2 instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376  # CentOS.
      InstanceType: t2.micro  # core ran
      KeyName: developerlabs
      Monitoring: true
      SecurityGroupIds:
        - sg-026e47fc05e0dc487
      SubnetId: subnet-0d06f412af157b0eb
      IamInstanceProfile: LabRole
      UserData:
        Fn::Base64: 
          !Sub |
           #!/bin/bash
           sudo yum -y update
           sudo amazon-linux-extras install nginx1 -y
           sudo systemctl start nginx
           sudo yum -y install ruby
           sudo yum -y install wget
           wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
           sudo chmod +x ./install
           sudo ./install auto
      Tags:
        -
          Key: Name
          Value: WEBSERVER